#!/usr/bin/env python3
"""Generate a GitHub Pages index for HTML experiment pages."""

from __future__ import annotations

import html
import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
EXPERIMENTS_DIR = ROOT / "_experiments"
OUTPUT_PATH = ROOT / "index.html"


INDEX_RE = re.compile(
    r"<!--\s*index:\s*(?P<title>.*?)\s*\|\s*(?P<date>.*?)\s*\|\s*(?P<desc>.*?)\s*-->",
    re.IGNORECASE | re.DOTALL,
)
TITLE_RE = re.compile(r"<title>(.*?)</title>", re.IGNORECASE | re.DOTALL)
DESC_RE = re.compile(
    r"<meta\s+name=[\"']description[\"']\s+content=[\"'](.*?)[\"']",
    re.IGNORECASE | re.DOTALL,
)


@dataclass
class Experiment:
    title: str
    date: str
    description: str
    href: str


def clean_text(value: str) -> str:
    return " ".join(html.unescape(value).split())


def parse_experiment(path: Path) -> Experiment:
    text = path.read_text(encoding="utf-8", errors="replace")
    index_match = INDEX_RE.search(text)
    if index_match:
        title = clean_text(index_match.group("title"))
        date = clean_text(index_match.group("date"))
        desc = clean_text(index_match.group("desc"))
    else:
        title_match = TITLE_RE.search(text)
        desc_match = DESC_RE.search(text)
        title = clean_text(title_match.group(1)) if title_match else path.stem
        date = ""
        desc = clean_text(desc_match.group(1)) if desc_match else ""

    href = path.relative_to(ROOT).as_posix()
    return Experiment(title=title, date=date, description=desc, href=href)


def load_experiments() -> list[Experiment]:
    if not EXPERIMENTS_DIR.exists():
        return []
    rows = [parse_experiment(path) for path in EXPERIMENTS_DIR.glob("*.html")]
    rows.sort(key=lambda item: (item.date, item.title), reverse=True)
    return rows


def render(experiments: list[Experiment]) -> str:
    cards = "\n".join(
        f"""
        <article class="card">
          <div class="date">{html.escape(exp.date or "No date")}</div>
          <h2><a href="{html.escape(exp.href)}">{html.escape(exp.title)}</a></h2>
          <p>{html.escape(exp.description)}</p>
          <a class="open" href="{html.escape(exp.href)}">Open page</a>
        </article>
        """
        for exp in experiments
    )
    if not cards:
        cards = '<div class="empty">No HTML experiments found in _experiments/.</div>'

    return f"""<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>HTML Experiments</title>
<style>
*{{box-sizing:border-box}}
body{{margin:0;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#f4f5f7;color:#111827}}
.hdr{{background:#111827;color:#fff;padding:22px 26px}}
.hdr h1{{font-size:22px;margin:0 0 6px;font-weight:750}}
.hdr p{{margin:0;color:rgba(255,255,255,.75);font-size:13px}}
.wrap{{max-width:1080px;margin:0 auto;padding:18px}}
.toolbar{{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px;color:#6b7280;font-size:12px}}
.grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:12px}}
.card{{background:#fff;border:1px solid #e2e4e8;border-radius:8px;padding:14px 16px;border-left:3px solid #1d4ed8}}
.card h2{{font-size:15px;line-height:1.45;margin:5px 0 8px}}
.card h2 a{{color:#1e3a5f;text-decoration:none}}
.card h2 a:hover{{text-decoration:underline}}
.card p{{font-size:12px;line-height:1.65;color:#4b5563;margin:0 0 12px}}
.date{{font-size:11px;color:#6b7280}}
.open{{display:inline-block;background:#111827;color:#fff;text-decoration:none;border-radius:5px;padding:6px 10px;font-size:12px;font-weight:650}}
.empty{{background:#fff;border:1px solid #e2e4e8;border-radius:8px;padding:28px;text-align:center;color:#6b7280}}
</style>
</head>
<body>
<header class="hdr">
  <h1>HTML Experiments</h1>
  <p>自动索引 _experiments/ 目录下的 HTML 页面。</p>
</header>
<main class="wrap">
  <div class="toolbar">
    <span>{len(experiments)} pages</span>
    <span>Generated by scripts/gen_index.py</span>
  </div>
  <section class="grid">
    {cards}
  </section>
</main>
</body>
</html>
"""


def main() -> int:
    experiments = load_experiments()
    OUTPUT_PATH.write_text(render(experiments), encoding="utf-8")
    print(f"wrote {OUTPUT_PATH}")
    print(f"indexed {len(experiments)} experiment pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
